openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /todo/update/status:
    post:
      tags:
      - todo-controller
      operationId: updateTodoStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoUpdateStatusRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Unit"
  /todo/delete/{id}:
    post:
      tags:
      - todo-controller
      operationId: deleteTodo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          minimum: 1
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Unit"
  /todo/create:
    post:
      tags:
      - todo-controller
      operationId: createTodo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoCreateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Unit"
  /todo/list:
    get:
      tags:
      - todo-controller
      operationId: getTodoList
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TodoResponse"
  /todo/detail/{id}:
    get:
      tags:
      - todo-controller
      operationId: getTodoDetail
      parameters:
      - name: id
        in: path
        required: true
        schema:
          minimum: 1
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TodoResponse"
components:
  schemas:
    TodoUpdateStatusRequest:
      required:
      - id
      - status
      type: object
      properties:
        id:
          minimum: 1
          type: integer
          format: int32
        status:
          maximum: 3
          minimum: 1
          type: integer
          format: int32
    Unit:
      type: object
    TodoCreateRequest:
      required:
      - category
      - status
      - title
      type: object
      properties:
        title:
          maxLength: 30
          minLength: 0
          type: string
        description:
          maxLength: 100
          minLength: 0
          type: string
        status:
          maximum: 3
          minimum: 1
          type: integer
          format: int32
        category:
          type: string
    TodoResponse:
      required:
      - category
      - createdAt
      - id
      - status
      - title
      - updatedAt
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - TODO
          - DOING
          - DONE
        category:
          type: string
          enum:
          - WORK
          - PRIVATE
          - HOBBY
          - OTHER
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
