spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
