server:
  port: 8090
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: batch
  profiles:
    active:
      - local
  server:
    port: 8090
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:database}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

application:
  cache:
    ttl-second: 30
